export const FETCH_UPCOMING_MOVIES = 'FETCH_UPCOMING_MOVIES';
export const FETCH_IN_THEATRES = 'FETCH_IN_THEATRES';
export const SEARCH_MOVIE = 'SEARCH_MOVIE';
export const GET_MOVIE = 'GET_MOVIE';

export const CLICKED_MOVIE = 'CLICKED_MOVIE';
